### ISSUE TITLE
Add YaCy engine and enable it by default

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/search#11]
According to this comment https://github.com/asciimoo/searx/issues/912#issuecomment-300024286 this is possible. By using this open source engine (not meta-engine, but a real one) we're encouraging them to continue growing.

**Comment by k09i71** [comment]
I'm sorry, was this a bad suggestion? No labels, no replies :(

**Comment by k09i71** [comment]
I'm sorry, was this a bad suggestion? No labels, no replies :disappointed_relieved:

**Comment by k09i71** [comment]
I'm sorry, was this a bad suggestion? This issue hasn't got labeled, no replies :disappointed_relieved:
