### ISSUE TITLE
.onion service

### ISSUE THREAD

**Issue by ndrwy** [privacytoolsIO/search#5]
Thank you so much for search.privacytools.io! I was wondering if offering it as an .onion service for Tor users is in scope. Thanks again :)

**Comment by jonaharagon** [comment]
Yes! That is a long term goal. Can't make any promises as to *when* at this moment but it'll happen.

**Comment by jonaharagon** [comment]
search.privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion. We're also using alt-svc to serve resources over Tor even when visitors use the clearnet domain, see [this blog post](https://write.privacytools.io/jonah/tor-on-privacytools-io) and [technical article](https://write.privacytools.io/jonah/securing-services-with-tor-and-alt-svc) for more details.
